server:
  port: 8081
spring:
  application:
    name: social_media
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/SocialMediaDB?createDatabaseIfNotExist=true
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
management:
  endpoint: #configuring health endpoint to show all the information instead of little
    health:
      show-details: always
  endpoints: #this configuration exposes all the endpoints of the actuator
    web:
      exposure:
        include: '*'
      base-path: '/admin'
  info:
    env:
      enabled: true
info:
  app:
    description: This application fetches all the connections of a user
    name: Social Media Connections Application
    version: 1.0


